---
title: "Deforestation_data"
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
library(ggplot2)
library(scales)

Figure1 <- read.csv("def_area_2004_2019.csv")
Figure2 <- read.csv("Amazonas_pop.csv")
```

```{r}
Figure1
```

```{r}
Figure2
```

```{r}
#| echo: false
#| message: false
#| warning: false
Figure1 |>
    ggplot(mapping = aes(x = Ano.Estados, y = AM)) +
    geom_point() +
    geom_line() +
    scale_y_continuous(limits = c(0, NA))+
    labs(y = "Amount of Deforestation (km²)", 
         x = "Year",
         title = "Figure 1",)
```

```{r}
#| echo: false
#| message: false
#| warning: false
Figure2 |>
    ggplot(mapping = aes(x = year, y = population)) +
    geom_point() +
    geom_line() +
    scale_y_continuous(
      limits = c(0, NA),
      labels = function(x) ifelse(x == 0, "0", paste0(label_number(scale = 1e-6, suffix = " million")(x)))
    ) +
    labs(y = "Population", 
         x = "Year",
         title = "Figure 2",)
```

